# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.AiEvalProbitOrdinal <- function(Z, D, Y, X, D_factor, ZX, rho, RSigma0_beta_inv, RSigma0_alpha_inv, Rsigma0, Rbeta, Ralpha, Rtheta, Rdelta, n_mcmc, verbose, out_length, Zbeta_off, theta01_off, lZX, C) {
    .Call(`_aihuman_AiEvalProbitOrdinal`, Z, D, Y, X, D_factor, ZX, rho, RSigma0_beta_inv, RSigma0_alpha_inv, Rsigma0, Rbeta, Ralpha, Rtheta, Rdelta, n_mcmc, verbose, out_length, Zbeta_off, theta01_off, lZX, C)
}

.CalAPCEj_ordinal_rcpp <- function(X, ZX, rho, beta, alpha, theta, delta, p, k, n, s1, s2, s3, s4, s5, lZX, C, C_binary, only_optimal_decision, D, D_binary, dmf, dmf_null, only_dmf_fair) {
    .Call(`_aihuman_CalAPCEj_ordinal_rcpp`, X, ZX, rho, beta, alpha, theta, delta, p, k, n, s1, s2, s3, s4, s5, lZX, C, C_binary, only_optimal_decision, D, D_binary, dmf, dmf_null, only_dmf_fair)
}

